### PR TITLE
Add slides on ORW

### PR DESCRIPTION
**Pull request by JakeOrchard**
Github seems to indicate that I made more changes than I did. I only added six slides at the end.

### CODE REVIEW

**Comment by johanneswieland** [comment]
Couple of issues:
1. Can you remove the pdf and the gz file from the push? I cannot resolve the conflict for the pdf.
2. I think slide 1 should be the PE new car calculation we have in the intro. It sets the stage that there is a puzzle here.

**Review by johanneswieland — CHANGES_REQUESTED** [review]
See comments in main pull request thread.

**Comment by JakeOrchard** [comment]
.pdf and .gz files have been removed. 

I added the Car Counterfactual as the first slide.

Hopefully, this is what you had in mind!

Jake

**Review by johanneswieland — APPROVED** [review]

**Review by johanneswieland — CHANGES_REQUESTED** [review]
The pdf is still in the pull request

**Comment by johanneswieland** [comment]
I am closing the pull request, because the initial pdf commit still causes a conflict. Can you update your main and then push the commits from another branch?

**Pull request closed without merging**
